#+title: Requirements

* Overview
For the final project, I will be creating my own programming language, called UC, or Untyped C. This language, as can be determined by the name, will be similar to C/C++ (because I have no creativity) but with weak typing. Then a Python program will translate that language into Python and execute it.

To use the program just run main.py <name of file>

* Syntax
** Variable Initialization
Variable initialization will look very similar to python but with a semicolon at the end. It will look like src_python{var = <value>;}.

** If
An if statement should look like:
#+begin_src C
if (/*condition>*/) {
    // code to execute if condition is met
}
#+end_src
Basically the same as C/C++.

** For
The format should be:
#+begin_src C
for (/*variable initialization*/ , /*variable condition*/, /*variable iteration*/) {
    // code to execute in loop
}
#+end_src

** While
A while loop will be the exact same as C.
#+begin_src C
while (/*condition*/) {
    // code to execute in loop
}
#+end_src

** Functions
Since there is no explicit typing, the syntax will slightly differ from C. Instead of starting the line with the return type of the function, function declaration will consist of the ~fn~ keyword.
#+begin_src C
fn NameOfFunction (/*params*/) {
    // code to execute in function
}
#+end_src

(For each of these, the opening curly bracket can be on the same line or the next line but the rest should be exactly the same)
